### ISSUE TITLE
Do you always need to have at least 1 migration?

### ISSUE THREAD

**Issue by Poltergeisen** [SRoddis/Mongo.Migration#11]
Do you need an initial migration? What if I have an entity that is version 1.0 and hasn't needed any migrations yet?

**Comment by Poltergeisen** [comment]
I fixed it by creating an "Initial Migration" with empty up/down methods. 

Do you think you might be able to add something to the readme about best practices for when you start a brand new project?

**Comment by SRoddis** [comment]
Hey Adam,

I will have a look and support you with a fix. 

Cheers,
Sean

**Comment by danijadeb** [comment]
Hi,

Was this ever implemented, as I have a set of seeders for initialising data, but I don't want to have to provide an empty migration for these?

Thanks
Dani
