### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by Maciejszuchta** [SRoddis/Mongo.Migration#12]
Hello,
I just installed your tool, and I'm wondering how to use it.
I have an ASP Core 2.2 application that connects to MongoDB. Followed your "How to use" section but no migrations get applied to the database.

I use it like this:
In startup.cs
```   
var client = new MongoClient(MongoDbConfiguration.ConnectionAuthString);
MongoMigration.Initialize();
```

since my database is already running and im only provideing connection string to my database.

I copy pased your example migration class:
```
   public class M001_First_Migration : Migration<ApplicationUser>
    {
        public M001_First_Migration() : base("0.0.1")
        {
        }

        public override void Up(BsonDocument document)
        {
            Console.WriteLine("Applaying migration");
            var doors = document["Users"].ToInt32();//Users is it the name of collection ?
            document.Add("Doors", doors);
        }

        public override void Down(BsonDocument document)
        {
            //var doors = document["Users"].ToInt32();
            //document.Add("Dors", doors);
            //document.Remove("Doors");
        }
    }
```

**Comment by SRoddis** [comment]
Hello Maciejszuchta,

did you add the annotation "Current Version" to "ApplicationUser"?

![image](https://user-images.githubusercontent.com/11769486/56205574-78ad9900-604a-11e9-9c17-1d19fb73d80b.png)

In the demo you can see exactly how to do it.

Currently, the migrations are made during the deserialization and are therefore only available in the memory. This makes it relatively easy to create a zero downtime deployment. This is the actual usecase for the library. Currently there is no automated update on the database. Of course you can save the migrated objects yourself and then they are in the database as well. (That happens with most CRUD applications anyway)

I am currently working on migrating the database to start the application. That would be another usecase.
In addition, I create a simple connection to .netcore applications.

Did that help you? For further questions, I am happy to be available.

Greetings,
Sean Roddis

**Comment by Maciejszuchta** [comment]
Thank you for the response. I figured out how to use your library. Good Job :)
I will wait for further updates with migration on application startup. 

Greetings

**Comment by SRoddis** [comment]
Hey Maciejszuchta,
I uploaded a new version of mongo.migration this weekend. I will adept the documentation this week.

But you can already test it. If you have any feedback let me know. I will close this Issue in 2 weeks, if you have no feedback.

Cheers,
Sean Roddis

**Comment by danijadeb** [comment]
Hey @SRoddis 
I am trying to use your tool, but since updating to your latest version, I am having a few issues with getting things up and running. 

Currently, I am getting this error:
```System.InvalidOperationException: Cannot resolve 'System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Hosting.IStartupFilter]' from root provider because it requires scoped service 'Mongo.Migration.IMongoMigration'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()```

I was wondering if you would be able to offer any support and point me in the right direction to fix this.
Thanks Dani

**Comment by SRoddis** [comment]
Hey danijadeb,

the error should be fixed now. Please have a look at the Readme, some of the attribute have been renamed. 

Cheers, Sean Roddis
