### ISSUE TITLE
Discover Migrations via Dependency Injection

### ISSUE THREAD

**Issue by glennsills** [SRoddis/Mongo.Migration#14]
Do you have any plans to provide a mechanism to define migrations using dependency injection. This would allow the injection of other services into the migrations which would be helpful in some situations.

**Comment by SRoddis** [comment]
Hey glennsills,

what would be the usecase?

Cheers, 
Sean

**Comment by glennsills** [comment]
If you are doing a migration that requires access to another data source. For example, you want to convert a zipcode filed to a zipcode + 4 field in a document containing an address. There are services that will return a zipcode + 4 if you provide it with the address.  So I'd like to inject the zipcode service into the migration. Or course, once you migration does some thing like this, you'd probably also want to inject ILogger :-)

**Comment by SRoddis** [comment]
Hey glennsills,

Mongo.Migration is for simple schema migrations that could be done at runtime. At the moment there is no dependency injection for migrations planned. Iam worried, that this can decrease the performance.

Maybe i have to split the mirgations between startup and runtime,  so in future its possible to do this on startup. I will have to think about this.

Logging will be added in the next version.

Cheers, Sean

**Comment by maxiptah** [comment]
One more usecase for DI in Migrations. We are storing in Mongo configurations of physical devices. Once the migration is run (e.g. a new capability is added) we want to notify the device that it should requery its configuration (and as a result e.g. provide more capabilities to end users).
So I would like to inject into Migration an IDeviceNotifier.

**Comment by SRoddis** [comment]
Hey @maxiptah,
sorry for late response.

I will have a look at this issue.

Cheers,
Sean Roddis

**Comment by SRoddis** [comment]
Hey @glennsills  @maxiptah,

please have a look at https://github.com/SRoddis/Mongo.Migration#dependency-injection and give me feedback. 

I will close this Issue otherwise. :)

Cheers, Sean
