### ISSUE TITLE
Support for Ssl settings for MongoDB API in Azure Cosmos DB

### ISSUE THREAD

**Issue by psmorandi** [SRoddis/Mongo.Migration#16]
Hello there,

Any plans to support SSL options when initializing the settings? For CosmosDB MongoDB API, unfortunately, I can't just use the SSL option in the connection string. I must also set the configuration `EnabledSslProtocols` as this example from Microsoft (it's shown at Azure Cosmos DB page after you create it):
```csharp
string connectionString = 
  @"mongodb://my-cosmosdb:someaccesskey@my-cosmosdb.documents.azure.com:10255/?ssl=true&replicaSet=globaldb";

MongoClientSettings settings = MongoClientSettings.FromUrl(
  new MongoUrl(connectionString)
);

settings.SslSettings = 
  new SslSettings() { EnabledSslProtocols = SslProtocols.Tls12 };
  
var mongoClient = new MongoClient(settings);
```

Connect without SSL is not an option for Azure Cosmos DB either (it's required). I guess this would be also useful for Atlas DB, but I'm not sure if it requires SSL.

Best Regards,

**Comment by SRoddis** [comment]
Hey Psmorandi,

i will update the configuration and push a new version of mongo.migration.

Thank you for the advice! That makes totaly sens. :)

Cheers, 
Sean

**Comment by SRoddis** [comment]
Hey @psmorandi,
sorry for late response. I had a lot of work to do.

I see two solutions for this issue. You could add a client to your DI-container, with the right setting. So the library will use this client. Or you can use the ClientSettings on the MongoMigrationSettings (I just added that possibility for that case).

Please give me Feedback, if that help you out.

Cheers,
Sean Roddis
