### ISSUE TITLE
Cannot DI a IMongoClient and Mongo.Migration services

### ISSUE THREAD

**Issue by DizWARE** [SRoddis/Mongo.Migration#17]
While using .Net Core 2.2 (Aspnetcore), if you add a IMongoClient into the dependency injector, you cannot add the migration services due to the following error:

```
System.InvalidOperationException: 'Unable to activate type 'Mongo.Migration.Migrations.CollectionMigrationRunner'. The following constructors are ambiguous:
Void .ctor(Microsoft.Extensions.Options.IOptions`1[Mongo.Migration.Startup.DotNetCore.MongoMigrationSettings], Mongo.Migration.Documents.Locators.ICollectionLocator, Mongo.Migration.Services.IVersionService, Mongo.Migration.Migrations.IMigrationRunner)
Void .ctor(MongoDB.Driver.IMongoClient, Mongo.Migration.Documents.Locators.ICollectionLocator, Mongo.Migration.Services.IVersionService, Mongo.Migration.Migrations.IMigrationRunner)'
```

Even if you have the MongoMigrationSettings configured and in the DI, it still runs into this issue but only if you are injecting a IMongoClient into the DI as well.

This issue specifically becomes more complicated because most of those services are internal, so there really is no way around the issue without physically rewriting the code.

**Comment by SRoddis** [comment]
Hey @DizWARE,

I tried to reproduce your issue, but i dindt get an exception. You should register a client or use the settings. 

Please have a look at "Quick Start" >> ".Net Core" >> 1.1 or 1.2

I released a new version of the library, maybe this resolves your issue? Please give me Feedback! 

Cheers,
Sean Roddis
