### ISSUE TITLE
Installation error (netstandard2.0)

### ISSUE THREAD

**Issue by vyshkant** [SRoddis/Mongo.Migration#18]
Hello!

I couldn’t install your library in a project based on `netstandard2.0`. Here is an error i've seen:

```
NU1202: Package Mongo.Migration 3.0.73 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Mongo.Migration 3.0.73 supports:
  - net47 (.NETFramework,Version=v4.7)
  - netcoreapp2.2 (.NETCoreApp,Version=v2.2)
Package restore failed. Rolling back package changes for 'My.Project.Name'.
```

Is it possible to make this library compatible with `netstandard2.0`?

**Comment by kernel-coder** [comment]
I need it too to support .NET Standard as I have a .NET Standard library that contains all of my data classes which is used by both .NET Core Web Api server and the .NET Framework 4.62 client app. Do you have any plan to support .NET Standard please?

**Comment by SRoddis** [comment]
Hey, sorry for the late response. 

I added .netstandard2.0 to the project. Please let me know if that fixes your problems. 
I will not go back to .NET Framework 4.6 support, so you have to migrate your project to 4.7 or change to .netCore.

If I dont get any Feedback in the next 3 weeks, I will close this issue. :)

Cheers, Sean

**Comment by kernel-coder** [comment]
@SRoddis  Thanks for the update. I'll give a try this weekend and will update you accordingly
