### ISSUE TITLE
Aggregates and Projections

### ISSUE THREAD

**Issue by shawnmclean** [SRoddis/Mongo.Migration#2]
Does it work with aggregate pipelines and projections?

In the `Dors` and `Doors` example, what happens in the case of a projection where I'd do:

`carCollection.someQuery().Select(c => new { Doors = c.Doors });`

This should attempt a field selection on mongo side on `doors` but there might exist `dors` instead.

Aggregate pipelines work within the schema on Mongo but the C# driver will try to build the query from the current model.

In cases like these, does the library intercept the request to mongo and transform those too?

**Comment by SRoddis** [comment]
Hey Shawn, 

in the first version aggregate pipelines, projections and updates are not supported (projection I have not testet, but I will on the weekend and let you know). It is a good point I have to add those to the Readme as well.

The library intercepts the GetSerializer() method from MongoDB C# Driver. In case the requested document is a IDocument the Serialize() and Deserialze() methods are decorated and migrate the document. 

Unfortunately I have to say that in this case the library does not intercepts the request. 
But I will add this to the list of features. 

Thank you for the Input! :)

Cheers, Sean Roddis.

**Comment by SRoddis** [comment]
Updated Readme.
