### ISSUE TITLE
Cannot setup migrations to existing db

### ISSUE THREAD

**Issue by rpyndus** [SRoddis/Mongo.Migration#28]
1. Added IDocument to document class
2. Initialized Version to new DocumentVersion(0, 0, 0);
3. Added required attributes
3. Seed documents to an empty database
4. service.AddMigrations

![image](https://user-images.githubusercontent.com/19654738/77061979-63b85300-69db-11ea-87f2-aa25cb6c40c0.png)

In debug mode, app is not even entering migrations Up method

If I seed db with documents without Version property, application is entering migrations Up method but after taking care of all documents its also throw an exception

![image](https://user-images.githubusercontent.com/19654738/77062606-7f702900-69dc-11ea-9f5c-91a263e91fd4.png)

Error occur after Up method affects all BsonDocuments
![image](https://user-images.githubusercontent.com/19654738/77062647-9282f900-69dc-11ea-8777-c7d5149c4331.png)

**Comment by SRoddis** [comment]
Hey, 
I added a line that should fix the Problem. Please update to version 3.0.105.

Cheers,
Sean
