### ISSUE TITLE
Unable to override Location interfaces.

### ISSUE THREAD

**Issue by darrenhull** [SRoddis/Mongo.Migration#30]
Hi,

The following interfaces are internal meaning that the functionality cannot be overridden: IStartUpVersionLocator, IRuntimeVersionLocator, IMigrationService, IStartUpVersionLocator.

Can these interfaces be changed to public please?

Thanks

**Comment by darrenhull** [comment]
Does the nuget package creation not get triggered on a merge?

**Comment by SRoddis** [comment]
Nope, I will do it later

**Comment by SRoddis** [comment]
package is updatet
