### ISSUE TITLE
Don't work Up and Down methods

### ISSUE THREAD

**Issue by hromau** [SRoddis/Mongo.Migration#38]
Hi

I'm trying to set and run migrations, but it isn't work for me. .Net Core 3.1, Web Api
In Startup.cs I have next:

         services.AddMvc();

            var _client = new MongoClient(ConnectionString);

            services.AddSingleton<IMongoClient>(_client);

            services.AddMigration(new MongoMigrationSettings
            {
                Database = DatabaseName,
            });

And next classes: 

     
    [RuntimeVersion("0.0.1")]
    public class Car : IDocument
    {
        public ObjectId Id { get; set; }

        public string Type { get; set; }

        public int Doors { get; set; }

        public DocumentVersion Version { get; set; }
    }
    
    public class M001_RenameDorsToDoors : DocumentMigration<Car>, IDatabaseMigration
    {
        public M001_RenameDorsToDoors()
            : base("0.0.1")
        {
        }

        public override void Up(BsonDocument document)
        {
            var doors = document["Dors"].ToInt32();
            document.Add("Doors", doors);
            document.Remove("Dors");
        }

        public override void Down(BsonDocument document)
        {
            var doors = document["Doors"].ToInt32();
            document.Add("Dors", doors);
            document.Remove("Doors");
        }

        public void Up(IMongoDatabase db)
        {
            throw new NotImplementedException();
        }

        public void Down(IMongoDatabase db)
        {
            throw new NotImplementedException();
        }
    }

No breakpoint has been hit in every method

**Comment by vd3d** [comment]
Same here... there is no error message, no log, no explanation :-(

**Comment by andreyciocan** [comment]
Same issue for me too...

**Comment by hromau** [comment]
public class FeedbackDatabaseMigration : DatabaseMigration
    {
        public FeedbackDatabaseMigration()
            : base("0.0.1")
        {
        }

        public override void Up(IMongoDatabase db)
        {
            // some of actions
        }

        public override void Down(IMongoDatabase db)
        {
            // some of actions
        }
    }

     public class FeedbackMigration : DocumentMigration<PendingFeedback>
     {
        public FeedbackMigration()
            : base("0.0.1")
        {
        }

        public override void Up(BsonDocument document)
        {
            // some of actions
        }

        public override void Down(BsonDocument document)
        {
            // some of actions
        }
    }


    [RuntimeVersion("0.0.1")]
    [CollectionLocation("PendingFeedbacks")]
    public class PendingFeedback : FeedbackBase, IDocument
    {
        public IEnumerable<ParticipantFeedbackForm> ParticipantFeedbackForms { get; set; }

        public DocumentVersion Version { get; set; }
    }



it worked for me
