### ISSUE TITLE
NoMigrationsFoundException

### ISSUE THREAD

**Issue by kavatari** [SRoddis/Mongo.Migration#46]
Hi guys, 

I am just starting some project with MongoDb to persist the data. In my experience at some point migrations for the database will be needed. So, I started testing your library and so far, I like it. But, at some point I am a little bit confused. 
When I use your library and I dont have any migrations so far, but I want my project to be prepared to migrate documents, the lib throws me the "NoMigrationsFoundException", after adding some "fake" document migration the exception is gone. 

What is the intention here for throwing this exception? Otherwise, I won't be able to prepare my project to manage migrations until the first migration will appear. 

https://github.com/SRoddis/Mongo.Migration/blob/6f00cf12657a49371d8eca875034395a91f2f42a/Mongo.Migration/Migrations/Locators/MigrationLocator.cs#L29

**Comment by trongnsy** [comment]
Hi guys,
I got the same issue.

In my project, I only need to add a new field to all existing objects one time in Startup.
I tried to use DatabaseMigration, it works well.
But when I ran the application, I always got NoMigrationsFoundException.
To fix this issue, I must fake a DocumentMigration (it does nothing). 

Please let me know I'm using this library correctly or not? And give me your suggestions, thanks!

**Comment by SRoddis** [comment]
Hey Guys, 
 
thank you for the Feedback. I changed the code to log a warning instead. 

Atm I switch the CI/CD to Github Actions. When I finish the migration, the new version will be avaiable at Nuget.

Cheers,
Sean
