### ISSUE TITLE
Migrate to NetStandard

### ISSUE THREAD

**Issue by TioLuiso** [SRoddis/Mongo.Migration#6]
Hello

I was looking for a MongoDb migrations library for C# and looks like yours is #1. Awesome!!!

I took a glance at it, and I had a couple of issues.

* It targets .NET 4.5. My project is in .NET Core.
* It defines a base interface and document. But I already have mine.

For the 2nd issue, I must give a thought. For the first, I have forked the repo and migrated to a project that multi targets .NET 4.5 and netstandard 2.0. However it looks like you have some nuget packing scripts and appveyor that I believe should be updated, and I'm not sure how to do it. Should I do a pull request?

Thanks a lot

P.S.: In the appveyor.yml, it looks like you have some keys. Hmmmm should they be there???

**Comment by SRoddis** [comment]
Hey Tio,
yes that would be nice. Just create the pull request and i will go through the changes and add everything to appveyor.

The keys in appvayor.yml are encrypted , so no worries. Thanks for the good work! :)

Sorry for responding  late, i was a bit busy.
Cheers, Sean Roddis

**Comment by TioLuiso** [comment]
Done. Let me know if I can do something

Thanks

**Comment by TioLuiso** [comment]
Suggestion: Instead of having a local Nuget.Exe, and having a nuspec that holds fixed dependencies, you could use the .NET core dotnet pack Mongo.Migration, which Will have a single nuget package with versions for net45 and netstandard2.0

**Comment by SRoddis** [comment]
Hey Tio,
I had a look on dotnet pack befor, but at the moment the library is ok with the nuget.exe. 

The next two weeks I will have holidays, so I have time to invest some work into the library. Maybe i switch to dotnet pack, but there is some work to do befor i can do this.

The changes to netstandard2.0 are added in the newest nuget.package. If you have any problems let me know.
Enjoy and leave a Star if you like the library! :)

Thanks for the good collaboration!
Cheers, Sean Roddis
