### ISSUE TITLE
NoMigrationFoundException on Debug in Visual Studio

### ISSUE THREAD

**Issue by Cular** [SRoddis/Mongo.Migration#8]
I would like to use your solution for mongo migration. But I've got the problem.
I've downloaded your demo and run it. It works perfectly as expected.
But when you remove all references to src(Mongo.Migration) and try to run demo.core with installed nuget pkg, you will get an error in Visual Studio.
![exception](https://user-images.githubusercontent.com/26927442/47649334-a3339480-db85-11e8-9d67-017932132266.png)

P.S. If you **publish** project, it works perfect.

Is this problem with VS (Community 2017 Version 15.8.8)? Or i miss some steps?

[Mongo.Migration-master.Test.zip](https://github.com/SRoddis/Mongo.Migration/files/2525187/Mongo.Migration-master.Test.zip)

UPD:
For some reason in class `MigrationLocator`
`var assemblies = AppDomain.CurrentDomain.GetAssemblies().ToList();` 
Does not touch assembly with "\*.MongoMigrations.dll", despite that run assembly (Main project) has reference on "\*.MongoMigrations" project.
And
`var migrationAssemblies = Directory.GetFiles(path, "*.MongoMigrations.dll").Select(Assembly.LoadFile);`
can't find assembly because Directory is nuget cache folder.

That is why nuget pkg does not working in debug mode, but published assembly works correctly.

**Comment by Cular** [comment]
Solution:
`var location = AppDomain.CurrentDomain.BaseDirectory;` 
instead 
`var location = Assembly.GetExecutingAssembly().Location;`

**Comment by CSharpBender** [comment]
Hi, can we have the update that Cular is proposing?

LE: As a workaround you can put &lt;CopyLocalLockFileAssemblies&gt;true&lt;/CopyLocalLockFileAssemblies&gt;  in the project.

**Comment by SRoddis** [comment]
Hey Cular and CSharpBender,

sry for the late answer. I dindt get the email from github with the issue. I will have a look on the problem and make a new release. Thank you for the feedback. :)

Cheers, Sean

**Comment by SRoddis** [comment]
Hey Guys,

I changed the code to use 
```
var location = AppDomain.CurrentDomain.BaseDirectory;
```
everything works as expected.

If you have any further feedback let me know. Otherwise I will close the issue next week. 

Please dont forget to star the project if you like the library. 

Cheers,
Sean Roddis
